apiVersion: apps/v1
kind: Deployment
metadata:
  name: utcdate-service-deployment
  labels:
    app: utcdate-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: utcdate-service
  template:
    metadata:
      labels:
        app: utcdate-service
    spec:
      containers:
      - name: utcdate
        image: pta19059/utcdate-service:latest
        ports:
        - containerPort: 3001
