apiVersion: apps/v1
kind: Deployment
metadata:
  name: isodate-service-deployment
  labels:
    app: isodate-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: isodate-service
  template:
    metadata:
      labels:
        app: isodate-service
    spec:
      containers:
      - name: isodate-service
        image: pta19059/isodate-service:latest
        ports:
        - containerPort: 3000
